// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.paifeaturestore.datasource;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class KKVData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static KKVData getRootAsKKVData(ByteBuffer _bb) { return getRootAsKKVData(_bb, new KKVData()); }
  public static KKVData getRootAsKKVData(ByteBuffer _bb, KKVData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KKVData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pk() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pkAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pkInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String sk() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer skAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer skInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long eventTimestamp() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public double playTime() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public int value(int j) { int o = __offset(12); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int valueLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector valueVector() { return valueVector(new ByteVector()); }
  public ByteVector valueVector(ByteVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createKKVData(FlatBufferBuilder builder,
      int pkOffset,
      int skOffset,
      long eventTimestamp,
      double playTime,
      int valueOffset) {
    builder.startTable(5);
    KKVData.addPlayTime(builder, playTime);
    KKVData.addEventTimestamp(builder, eventTimestamp);
    KKVData.addValue(builder, valueOffset);
    KKVData.addSk(builder, skOffset);
    KKVData.addPk(builder, pkOffset);
    return KKVData.endKKVData(builder);
  }

  public static void startKKVData(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addPk(FlatBufferBuilder builder, int pkOffset) { builder.addOffset(0, pkOffset, 0); }
  public static void addSk(FlatBufferBuilder builder, int skOffset) { builder.addOffset(1, skOffset, 0); }
  public static void addEventTimestamp(FlatBufferBuilder builder, long eventTimestamp) { builder.addLong(2, eventTimestamp, 0L); }
  public static void addPlayTime(FlatBufferBuilder builder, double playTime) { builder.addDouble(3, playTime, 0.0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(4, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createValueVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endKKVData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KKVData get(int j) { return get(new KKVData(), j); }
    public KKVData get(KKVData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

