// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.paifeaturestore.datasource;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class KKVRecordBlock extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static KKVRecordBlock getRootAsKKVRecordBlock(ByteBuffer _bb) { return getRootAsKKVRecordBlock(_bb, new KKVRecordBlock()); }
  public static KKVRecordBlock getRootAsKKVRecordBlock(ByteBuffer _bb, KKVRecordBlock obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KKVRecordBlock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.aliyun.openservices.paifeaturestore.datasource.KKVData values(int j) { return values(new com.aliyun.openservices.paifeaturestore.datasource.KKVData(), j); }
  public com.aliyun.openservices.paifeaturestore.datasource.KKVData values(com.aliyun.openservices.paifeaturestore.datasource.KKVData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int valuesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public com.aliyun.openservices.paifeaturestore.datasource.KKVData.Vector valuesVector() { return valuesVector(new com.aliyun.openservices.paifeaturestore.datasource.KKVData.Vector()); }
  public com.aliyun.openservices.paifeaturestore.datasource.KKVData.Vector valuesVector(com.aliyun.openservices.paifeaturestore.datasource.KKVData.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKKVRecordBlock(FlatBufferBuilder builder,
      int valuesOffset) {
    builder.startTable(1);
    KKVRecordBlock.addValues(builder, valuesOffset);
    return KKVRecordBlock.endKKVRecordBlock(builder);
  }

  public static void startKKVRecordBlock(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValues(FlatBufferBuilder builder, int valuesOffset) { builder.addOffset(0, valuesOffset, 0); }
  public static int createValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKKVRecordBlock(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishKKVRecordBlockBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedKKVRecordBlockBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KKVRecordBlock get(int j) { return get(new KKVRecordBlock(), j); }
    public KKVRecordBlock get(KKVRecordBlock obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

